/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/namlapan-studio.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function NamlapanStudio(props) {
  const group = React.useRef();
  // Update to your R2 bucket public URL
  const modelUrl = import.meta.env.VITE_MODEL_URL || "models/namlapan-studio.glb";
  const { nodes, materials, animations } = useGLTF(modelUrl);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="clap_arm"
          position={[-3.612, 45.309, 0.003]}
          rotation={[0, 1.542, 0]}
          scale={3.853}
        >
          <group name="body_b" rotation={[-Math.PI, 0, 0]}>
            <group name="top_b" rotation={[-Math.PI, 0, 0]}>
              <group name="top_b_end" position={[0, 0.305, 0]} />
            </group>
          </group>
          <mesh
            name="clap_board"
            geometry={nodes.clap_board.geometry}
            material={materials["clap boad"]}
            position={[-8.868, -7.407, -3.258]}
            rotation={[-1.567, -0.032, 0.573]}
            scale={0.164}
          />
        </group>
        <group
          name="Cube072"
          position={[8.426, 22.446, -18.984]}
          scale={[1.547, 1.547, 1.65]}
        >
          <mesh
            name="Cube024"
            geometry={nodes.Cube024.geometry}
            material={materials["hitam metalic"]}
          />
          <mesh
            name="Cube024_1"
            geometry={nodes.Cube024_1.geometry}
            material={materials.kameradepan}
          />
          <mesh
            name="Cube024_2"
            geometry={nodes.Cube024_2.geometry}
            material={materials["ALUMINIUM.098"]}
          />
          <mesh
            name="Cube024_3"
            geometry={nodes.Cube024_3.geometry}
            material={materials[" black"]}
          />
          <mesh
            name="Cube024_4"
            geometry={nodes.Cube024_4.geometry}
            material={materials["ALUMINIUM.052"]}
          />
        </group>
        <mesh
          name="Circle018"
          geometry={nodes.Circle018.geometry}
          material={materials.hitam}
          position={[-30.266, 29.747, -1.72]}
          rotation={[Math.PI, -1.558, Math.PI]}
          scale={12.217}
        />
        <mesh
          name="Camera"
          geometry={nodes.Camera.geometry}
          material={materials["#CAM0001_Textures"]}
          position={[-29.949, 32.009, -1.718]}
          rotation={[Math.PI, -1.555, Math.PI]}
          scale={41.445}
        />
        <group name="Laptop" position={[-17.471, 16.608, 24.92]} scale={2.457}>
          <mesh
            name="Cube003"
            geometry={nodes.Cube003.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube003_1"
            geometry={nodes.Cube003_1.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube003_2"
            geometry={nodes.Cube003_2.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube003_3"
            geometry={nodes.Cube003_3.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            name="Cube003_4"
            geometry={nodes.Cube003_4.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube003_5"
            geometry={nodes.Cube003_5.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cube003_6"
            geometry={nodes.Cube003_6.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Cube003_7"
            geometry={nodes.Cube003_7.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube003_8"
            geometry={nodes.Cube003_8.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube003_9"
            geometry={nodes.Cube003_9.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube003_10"
            geometry={nodes.Cube003_10.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube003_11"
            geometry={nodes.Cube003_11.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Cube003_12"
            geometry={nodes.Cube003_12.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            name="Cube003_13"
            geometry={nodes.Cube003_13.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.015"]}
          position={[-56.828, 5.208, 0]}
          scale={53.803}
        />
        <group
          name="Cover_Chair"
          position={[-73.861, 5.649, 0]}
          rotation={[Math.PI / 2, 0, -1.547]}
          scale={0.266}
        >
          <mesh
            name="Cover_Chair_1"
            geometry={nodes.Cover_Chair_1.geometry}
            material={materials.phong1SG}
          />
          <mesh
            name="Cover_Chair_2"
            geometry={nodes.Cover_Chair_2.geometry}
            material={materials.ig_100_100_100SG}
          />
        </group>
        <group
          name="iPhone__12_Pro"
          position={[-18.562, 16.523, 18.926]}
          rotation={[-0.011, 0.892, -3.133]}
          scale={3.64}
        >
          <mesh
            name="Plane007"
            geometry={nodes.Plane007.geometry}
            material={materials.BodyFrame}
          />
          <mesh
            name="Plane007_1"
            geometry={nodes.Plane007_1.geometry}
            material={materials.GrayGlossy2}
          />
          <mesh
            name="Plane007_2"
            geometry={nodes.Plane007_2.geometry}
            material={materials["Microphone/Speaker"]}
          />
          <mesh
            name="Plane007_3"
            geometry={nodes.Plane007_3.geometry}
            material={materials.Antenna}
          />
          <mesh
            name="iPhone12_Pro"
            geometry={nodes.iPhone12_Pro.geometry}
            material={materials.Body}
          >
            <mesh
              name="Apple_Logo"
              geometry={nodes.Apple_Logo.geometry}
              material={materials.Logo}
            />
            <mesh
              name="Bezel"
              geometry={nodes.Bezel.geometry}
              material={materials.bezel}
            >
              <group name="FrontCamera">
                <mesh
                  name="Sphere"
                  geometry={nodes.Sphere.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Sphere_1"
                  geometry={nodes.Sphere_1.geometry}
                  material={materials.FrontCamera}
                />
                <mesh
                  name="Sphere_2"
                  geometry={nodes.Sphere_2.geometry}
                  material={materials.Cameralens}
                />
              </group>
              <mesh
                name="FrontCamera001"
                geometry={nodes.FrontCamera001.geometry}
                material={materials["bezel.001"]}
                position={[0, -0.001, 0]}
              />
              <group name="FrontMic">
                <mesh
                  name="Sphere002"
                  geometry={nodes.Sphere002.geometry}
                  material={materials.GrayGlossy2}
                />
                <mesh
                  name="Sphere002_1"
                  geometry={nodes.Sphere002_1.geometry}
                  material={materials["Microphone/Speaker"]}
                />
              </group>
            </mesh>
            <group name="Camera1">
              <mesh
                name="Circle"
                geometry={nodes.Circle.geometry}
                material={materials.PacificBlue}
              />
              <mesh
                name="Circle_1"
                geometry={nodes.Circle_1.geometry}
                material={materials.Glass}
              />
              <mesh
                name="Circle_2"
                geometry={nodes.Circle_2.geometry}
                material={materials.GrayGlossy}
              />
              <mesh
                name="Circle_3"
                geometry={nodes.Circle_3.geometry}
                material={materials.Blackmatte}
              />
              <mesh
                name="Circle_4"
                geometry={nodes.Circle_4.geometry}
                material={materials.FrontCamera}
              />
              <mesh
                name="Circle_5"
                geometry={nodes.Circle_5.geometry}
                material={materials.Cameralens}
              />
            </group>
            <group name="Camera2">
              <mesh
                name="Circle005"
                geometry={nodes.Circle005.geometry}
                material={materials.PacificBlue}
              />
              <mesh
                name="Circle005_1"
                geometry={nodes.Circle005_1.geometry}
                material={materials.Glass}
              />
              <mesh
                name="Circle005_2"
                geometry={nodes.Circle005_2.geometry}
                material={materials.GrayGlossy}
              />
              <mesh
                name="Circle005_3"
                geometry={nodes.Circle005_3.geometry}
                material={materials.Blackmatte}
              />
              <mesh
                name="Circle005_4"
                geometry={nodes.Circle005_4.geometry}
                material={materials.FrontCamera}
              />
              <mesh
                name="Circle005_5"
                geometry={nodes.Circle005_5.geometry}
                material={materials.Cameralens}
              />
            </group>
            <group name="Camera3">
              <mesh
                name="Circle003"
                geometry={nodes.Circle003.geometry}
                material={materials.PacificBlue}
              />
              <mesh
                name="Circle003_1"
                geometry={nodes.Circle003_1.geometry}
                material={materials.Glass}
              />
              <mesh
                name="Circle003_2"
                geometry={nodes.Circle003_2.geometry}
                material={materials.GrayGlossy}
              />
              <mesh
                name="Circle003_3"
                geometry={nodes.Circle003_3.geometry}
                material={materials.Blackmatte}
              />
              <mesh
                name="Circle003_4"
                geometry={nodes.Circle003_4.geometry}
                material={materials.FrontCamera}
              />
              <mesh
                name="Circle003_5"
                geometry={nodes.Circle003_5.geometry}
                material={materials.Cameralens}
              />
            </group>
            <mesh
              name="CameraModule001"
              geometry={nodes.CameraModule001.geometry}
              material={materials.Glass}
            />
            <mesh
              name="CameraModule002"
              geometry={nodes.CameraModule002.geometry}
              material={materials["Microphone/Speaker"]}
            />
            <group name="Flash">
              <mesh
                name="Circle008"
                geometry={nodes.Circle008.geometry}
                material={materials.Flash2}
              />
              <mesh
                name="Circle008_1"
                geometry={nodes.Circle008_1.geometry}
                material={materials.Flash}
              />
            </group>
            <mesh
              name="LiDar"
              geometry={nodes.LiDar.geometry}
              material={materials["LiDar "]}
            />
            <mesh
              name="Screen"
              geometry={nodes.Screen.geometry}
              material={materials.Wallpaper}
            />
          </mesh>
          <mesh
            name="MuteButton"
            geometry={nodes.MuteButton.geometry}
            material={materials.BodyFrame}
          />
          <group name="Port">
            <mesh
              name="Circle004"
              geometry={nodes.Circle004.geometry}
              material={materials.Blackmatte}
            />
            <mesh
              name="Circle004_1"
              geometry={nodes.Circle004_1.geometry}
              material={materials.BodyFrame}
            />
          </group>
          <mesh
            name="PowerButton"
            geometry={nodes.PowerButton.geometry}
            material={materials.BodyFrame}
          />
          <group name="SimTray">
            <mesh
              name="Circle011"
              geometry={nodes.Circle011.geometry}
              material={materials.Blackmatte}
            />
            <mesh
              name="Circle011_1"
              geometry={nodes.Circle011_1.geometry}
              material={materials.BodyFrame}
            />
          </group>
          <mesh
            name="VolumeButton"
            geometry={nodes.VolumeButton.geometry}
            material={materials.BodyFrame}
          />
        </group>
        <mesh
          name="lens"
          geometry={nodes.lens.geometry}
          material={materials.Spotlight}
          position={[-21.27, 8.243, -37.358]}
          rotation={[0, -0.897, 0]}
          scale={19.628}
        />
        <group
          name="Light_Right"
          position={[-45.661, 26.327, 37.885]}
          rotation={[0, -0.838, 0.028]}
          scale={26.532}
        >
          <mesh
            name="Light_Body"
            geometry={nodes.Light_Body.geometry}
            material={materials["Worklight Plastic Main"]}
          />
          <mesh
            name="Light_Body_1"
            geometry={nodes.Light_Body_1.geometry}
            material={materials["Worklight Smooth Set"]}
          />
          <mesh
            name="Light_Body_2"
            geometry={nodes.Light_Body_2.geometry}
            material={materials["Worklight Paint Main"]}
          />
          <mesh
            name="Light_Body_3"
            geometry={nodes.Light_Body_3.geometry}
            material={materials["Worklight Light"]}
          />
          <mesh
            name="Light_Body_4"
            geometry={nodes.Light_Body_4.geometry}
            material={materials["Worklight Glass"]}
          />
          <mesh
            name="Light_Body_5"
            geometry={nodes.Light_Body_5.geometry}
            material={materials["Worklight Procedural Plastic"]}
          />
        </group>
        <group
          name="Industrial_Table"
          position={[-16.023, 4.866, 24.787]}
          rotation={[0, 1.561, 0]}
          scale={16.979}
        >
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["Table wood 1"]}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials["Old Steel"]}
          />
        </group>
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials.Material}
          position={[-29.126, 33.232, -1.653]}
          rotation={[0, 0, 1.573]}
          scale={0.465}
        />
      </group>
    </group>
  );
}

// Preload from R2 or local fallback
const modelUrl = import.meta.env.VITE_MODEL_URL || "models/namlapan-studio.glb";
useGLTF.preload(modelUrl);
