/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PhotoStudioOke.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PhotoStudio(props) {
  const { nodes, materials } = useGLTF('/models/PhotoStudioOke.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor.geometry} material={materials.Floor} rotation={[-Math.PI, 0, 0]} scale={[-5.047, -1, -4.454]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-3.854, 0.941, 0]} scale={0.645} />
      <mesh geometry={nodes.Tripod.geometry} material={materials.Monitor} position={[0.336, 0.812, -0.011]} rotation={[-Math.PI, 0.528, 0]} scale={[0.169, 0.186, 0.169]} />
      <group position={[-0.87, 1.742, 2.441]} rotation={[0, -0.655, 0]} scale={1.278}>
        <mesh geometry={nodes.Circle005.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials.LightEmit} />
      </group>
      <group position={[2, 0.546, 2.686]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials.BasicMeta} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.Table} />
      </group>
      <mesh geometry={nodes.KeyBoard.geometry} material={materials.Tech} position={[2.159, 1.086, 2.651]} scale={[0.017, 0.046, 0.026]} />
      <group position={[1.863, 1.058, 2.421]} scale={[0.029, 0.078, 0.136]}>
        <mesh geometry={nodes.Plane033.geometry} material={materials.Monitor} />
        <mesh geometry={nodes.Plane033_1.geometry} material={materials.Screen} />
      </group>
      <mesh geometry={nodes.Mouse.geometry} material={materials.Tech} position={[2.162, 1.11, 2.054]} scale={0.116} />
      <mesh geometry={nodes['00Stool'].geometry} material={nodes['00Stool'].material} position={[-2.83, 0.515, 7.282]} rotation={[0, Math.PI / 4, 0]} scale={0.104} />
      <group position={[0.27, 1.637, 0.011]} scale={0.026}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.Tech} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.Screen} />
      </group>
      <group position={[-2.361, 2.27, -3.368]} rotation={[0, 1.203, -Math.PI / 2]} scale={0.284}>
        <mesh geometry={nodes.Plane012.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.LightEmit} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.Lights2} />
      </group>
      <group position={[-2.375, 2.27, 3.595]} rotation={[0, -0.836, -Math.PI / 2]} scale={0.284}>
        <mesh geometry={nodes.Plane012.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.LightEmit} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.Lights2} />
      </group>
      <group position={[-3.705, 3.747, 0]} scale={[1, 1, 1.601]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.LightEmit} />
      </group>
      <group position={[6.262, 3.586, 2.152]} scale={0.169}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials.LightEmit} />
      </group>
      <group position={[6.262, 3.586, 0.365]} scale={0.169}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials.LightEmit} />
      </group>
      <group position={[6.262, 3.586, -2.221]} scale={0.169}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials.LightEmit} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.VolumeTest} position={[3.605, 2.151, 0.024]} scale={[8.997, 3.009, 5.134]} visible={false} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[21.358, 4.337, -0.429]} rotation={[Math.PI, 0, 0]} scale={[0.056, 0.073, 0.056]} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[21.109, 4.455, -0.454]} rotation={[Math.PI, 0.144, 0]} />
      <group position={[4.047, 0, 3.454]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.Monitor} />
      </group>
      <group position={[6.047, 0, 2.225]}>
        <mesh geometry={nodes.Plane017.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Plane017_2.geometry} material={materials.Monitor} />
      </group>
      <mesh geometry={nodes.Curve.geometry} material={materials.Material} position={[-3.425, 0.847, 1.23]} rotation={[1.682, 0.119, -1.692]} scale={10.585} />
      <mesh geometry={nodes.Curve016.geometry} material={materials['SVGMat.001']} />
    </group>
  )
}

useGLTF.preload('/models/PhotoStudioOke.glb')
